reservation_homepage:
    path:     /
    defaults: { _controller: ReservationBundle:Default:index }

reservation_payment:
    path:     /payment
    defaults: { _controller: ReservationBundle:Default:payment }

validation_payment:
    path:     /payment/validation
    defaults: { _controller: ReservationBundle:Default:validation }
