services:
#    reservation.example:
#        class: ReservationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    reservation_capacity:
        class: ReservationBundle\Capacity\Capacity
        arguments:
            - "@doctrine.orm.entity_manager"
            - %maxCapacity%

    command_payment:
        class: ReservationBundle\Payment\Payment

    send_mail:
        class: ReservationBundle\SendMail\SendMail
        arguments:
            - "@Mailer"
            - "@twig"